### ISSUE TITLE
Différence de kilométrage 

### ISSUE THREAD

**Issue by DidierBernard81** [Endo13/BikeEquipmentManager#20]
Quelque soit le fichier importé (Fit, Gpx, Tcx exportés depuis Garmin connect) ou Gpx (exporté depuis Stava) le kilométrage ne correspond pas à ceux affichés dans Garmin connect ou dans strava. La distance réelle est bien écrite au début des fichiers Tcx
        <DistanceMeters>75917.42</DistanceMeters>

**Comment by Endo13** [comment]
corrigé en version 1.0.1
